/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(interno)'}/cadastro/buscar-id` | `/cadastro/buscar-id`; params?: Router.UnknownInputParams; } | { pathname: `${'/(interno)'}/cadastro/cadastro-check` | `/cadastro/cadastro-check`; params?: Router.UnknownInputParams; } | { pathname: `${'/(interno)'}/cadastro/cadastro` | `/cadastro/cadastro`; params?: Router.UnknownInputParams; } | { pathname: `${'/(interno)'}/consulta/consultas` | `/consulta/consultas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(interno)'}/consulta/espera` | `/consulta/espera`; params?: Router.UnknownInputParams; } | { pathname: `${'/(interno)'}/tela-inicial` | `/tela-inicial`; params?: Router.UnknownInputParams; } | { pathname: `${'/(interno)'}/urgente/urgente` | `/urgente/urgente`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(interno)'}/cadastro/buscar-id` | `/cadastro/buscar-id`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(interno)'}/cadastro/cadastro-check` | `/cadastro/cadastro-check`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(interno)'}/cadastro/cadastro` | `/cadastro/cadastro`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(interno)'}/consulta/consultas` | `/consulta/consultas`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(interno)'}/consulta/espera` | `/consulta/espera`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(interno)'}/tela-inicial` | `/tela-inicial`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(interno)'}/urgente/urgente` | `/urgente/urgente`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(interno)'}/cadastro/buscar-id${`?${string}` | `#${string}` | ''}` | `/cadastro/buscar-id${`?${string}` | `#${string}` | ''}` | `${'/(interno)'}/cadastro/cadastro-check${`?${string}` | `#${string}` | ''}` | `/cadastro/cadastro-check${`?${string}` | `#${string}` | ''}` | `${'/(interno)'}/cadastro/cadastro${`?${string}` | `#${string}` | ''}` | `/cadastro/cadastro${`?${string}` | `#${string}` | ''}` | `${'/(interno)'}/consulta/consultas${`?${string}` | `#${string}` | ''}` | `/consulta/consultas${`?${string}` | `#${string}` | ''}` | `${'/(interno)'}/consulta/espera${`?${string}` | `#${string}` | ''}` | `/consulta/espera${`?${string}` | `#${string}` | ''}` | `${'/(interno)'}/tela-inicial${`?${string}` | `#${string}` | ''}` | `/tela-inicial${`?${string}` | `#${string}` | ''}` | `${'/(interno)'}/urgente/urgente${`?${string}` | `#${string}` | ''}` | `/urgente/urgente${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(interno)'}/cadastro/buscar-id` | `/cadastro/buscar-id`; params?: Router.UnknownInputParams; } | { pathname: `${'/(interno)'}/cadastro/cadastro-check` | `/cadastro/cadastro-check`; params?: Router.UnknownInputParams; } | { pathname: `${'/(interno)'}/cadastro/cadastro` | `/cadastro/cadastro`; params?: Router.UnknownInputParams; } | { pathname: `${'/(interno)'}/consulta/consultas` | `/consulta/consultas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(interno)'}/consulta/espera` | `/consulta/espera`; params?: Router.UnknownInputParams; } | { pathname: `${'/(interno)'}/tela-inicial` | `/tela-inicial`; params?: Router.UnknownInputParams; } | { pathname: `${'/(interno)'}/urgente/urgente` | `/urgente/urgente`; params?: Router.UnknownInputParams; };
    }
  }
}
