/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(interno)'}/buscar-id` | `/buscar-id`; params?: Router.UnknownInputParams; } | { pathname: `${'/(interno)'}/cadastro-check` | `/cadastro-check`; params?: Router.UnknownInputParams; } | { pathname: `${'/(interno)'}/cadastro` | `/cadastro`; params?: Router.UnknownInputParams; } | { pathname: `${'/(interno)'}/consultas` | `/consultas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(interno)'}/espera` | `/espera`; params?: Router.UnknownInputParams; } | { pathname: `${'/(interno)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(interno)'}/urgente` | `/urgente`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(interno)'}/buscar-id` | `/buscar-id`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(interno)'}/cadastro-check` | `/cadastro-check`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(interno)'}/cadastro` | `/cadastro`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(interno)'}/consultas` | `/consultas`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(interno)'}/espera` | `/espera`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(interno)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(interno)'}/urgente` | `/urgente`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(interno)'}/buscar-id${`?${string}` | `#${string}` | ''}` | `/buscar-id${`?${string}` | `#${string}` | ''}` | `${'/(interno)'}/cadastro-check${`?${string}` | `#${string}` | ''}` | `/cadastro-check${`?${string}` | `#${string}` | ''}` | `${'/(interno)'}/cadastro${`?${string}` | `#${string}` | ''}` | `/cadastro${`?${string}` | `#${string}` | ''}` | `${'/(interno)'}/consultas${`?${string}` | `#${string}` | ''}` | `/consultas${`?${string}` | `#${string}` | ''}` | `${'/(interno)'}/espera${`?${string}` | `#${string}` | ''}` | `/espera${`?${string}` | `#${string}` | ''}` | `${'/(interno)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(interno)'}/urgente${`?${string}` | `#${string}` | ''}` | `/urgente${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(interno)'}/buscar-id` | `/buscar-id`; params?: Router.UnknownInputParams; } | { pathname: `${'/(interno)'}/cadastro-check` | `/cadastro-check`; params?: Router.UnknownInputParams; } | { pathname: `${'/(interno)'}/cadastro` | `/cadastro`; params?: Router.UnknownInputParams; } | { pathname: `${'/(interno)'}/consultas` | `/consultas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(interno)'}/espera` | `/espera`; params?: Router.UnknownInputParams; } | { pathname: `${'/(interno)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(interno)'}/urgente` | `/urgente`; params?: Router.UnknownInputParams; };
    }
  }
}
